Added hover effects on issues to grab section cards
AmanSarraf/Opensource-Buddy pull request #36
Opened 2022-10-14 14:51 UTC by cleverhare

As I have generate an Issue

2022-10-14 18:36 UTC, AmanSarraf requested changes

2022-10-14 18:36 UTC, AmanSarraf commented on index.html
> +    <link rel="stylesheet" href="./css/cleverhare.css">
Please rename the CSS file to something more relevant, that might not result in any future fellow contributors
For Example : 
````suggestion
    <link rel="stylesheet" href="./css/Issues_hover.css">
````

2022-10-15 05:02 UTC, cleverhare commented on index.html
> +    <link rel="stylesheet" href="./css/cleverhare.css">
Sure

2022-10-15 05:03 UTC, cleverhare commented
Done

2022-10-15 05:38 UTC, AmanSarraf requested changes

2022-10-15 05:38 UTC, AmanSarraf commented on index.html
> +    <link rel="stylesheet" href="./css/Issues_hover.css">
need to rename the css file name as well , check It's cleverhare.css  should be >>>>>>> Issues_hover.css instead.
else the stylesheet wont be linked.
Also update your fork before raising PR,The latest branch is updated last night.

2022-10-15 06:32 UTC, cleverhare commented on index.html
> +    <link rel="stylesheet" href="./css/Issues_hover.css">
Okay brother

2022-10-15 06:42 UTC, closed without merging

2022-10-15 06:42 UTC, cleverhare commented
Generated another one